### ISSUE TITLE
Feature – Add Czech language

### ISSUE THREAD

**Issue by krychtor** [talosross/SummaryYou#2]
Hi,
Is it possible to add Czech language? I would love to translate it.

Thanks!

**Comment by talosross** [comment]
Great that you want to help, I just uploaded a new file under /app/src/main/res
/values-cs/strings.xml. Type in your translation and create a pull request.

**Comment by krychtor** [comment]
Thank you!

**Comment by talosross** [comment]
If you want me to integrate it, you have to send me the file.

**Comment by krychtor** [comment]
Hi,
I’m very sorry for a late reply. I had a lot of school stuff to do, and I haven’t been able to focus much on other things.¨
Anyway, here’s the file:
https://krychtalek.link/T2yzyE

(Because I couldn’t upload .xml file here, I uploaded it to my Sharepoint, if that’s okay.)

Best regards
xdws
