### ISSUE TITLE
Use secure https

### ISSUE THREAD

**Issue by pablo03v** [talosross/SummaryYou#3]
Currently the app connects to google every time I do a summary. Without this http (80) connection, the app will say that it has no internet connection.

Please upgrade this request to https :)

**Comment by pablo03v** [comment]
![e8b9758a-227e-4bdb-bbe8-a95efda01ff8.png](https://github.com/talosross/SummaryYou/assets/93644977/af7d1251-05ac-48e8-a664-39a7f10c703f)

![d6e4ddc1-dded-4733-9003-83db25b5307e.png](https://github.com/talosross/SummaryYou/assets/93644977/3e6cb1cc-41a1-4875-8532-7dab7889b78e)

**Comment by talosross** [comment]
Fixed and now using https://www.wikipedia.org instead of http://google.com.
