### ISSUE TITLE
Null object reference

### ISSUE THREAD

**Issue by pablo03v** [talosross/SummaryYou#4]
No matter which site I try, it always ends up in the same error:

![6f5aaa00-cdef-4ded-ba5b-70ebf7dc2bf3.png](https://github.com/talosross/SummaryYou/assets/93644977/37fa8069-0152-45c7-a69d-cd4d1ea71694)

**Comment by talosross** [comment]
I can't reproduce this can you send me the URL that isn't working?

**Comment by pablo03v** [comment]
literally none of them is. Go ahead and test it with https://overload.pablos.cloud for example

**Comment by talosross** [comment]
I can't reproduce this, try to reinstall the apk.

**Comment by pablo03v** [comment]
Ok, I will :)

**Comment by kid1412621** [comment]
I got the same issue. Is that caused by not providing OpenAI API key?

**Comment by NikunjK8** [comment]
Same here

**Comment by talosross** [comment]
So far I know that's because of a false key ,  no key and too long input texts. I'm trying to add better log.

**Comment by talosross** [comment]
Resolved, an important line was missing.
